AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
  NewCops: enable
  TargetRubyVersion: 2.6.5
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 40
  Exclude:
    - 'spec/**/*'